/* FunLab core — experiment registry: the single source of truth for cards,
   search, categories and related-experiment suggestions. */
window.FunLab = window.FunLab || {};
(function (FL) {
  "use strict";

  FL.registry = [
    {
      id: "click-rush",
      title: "Click Rush",
      desc: "Ten seconds, one button. How many taps can you land — and what's your CPS?",
      category: "Arcade",
      color: "var(--coral)", tint: "var(--coral-tint)",
      icon: "click-rush",
      path: "experiments/click-rush/",
      tags: ["click", "cps", "speed", "tap", "button", "reflex"],
      featured: false,
    },
    {
      id: "reaction-lab",
      title: "Reaction Lab",
      desc: "Wait for green, then tap instantly. Five rounds of pure reflex testing.",
      category: "Arcade",
      color: "var(--sky)", tint: "var(--sky-tint)",
      icon: "reaction-lab",
      path: "experiments/reaction-lab/",
      tags: ["reaction", "reflex", "green", "ms", "speed", "timer"],
      featured: false,
    },
    {
      id: "gravity-playground",
      title: "Gravity Playground",
      desc: "Spawn balls, throw them around, and tune gravity and bounce in a tiny physics universe.",
      category: "Physics",
      color: "var(--brand)", tint: "var(--brand-tint)",
      icon: "gravity-playground",
      path: "experiments/gravity-playground/",
      tags: ["physics", "gravity", "balls", "sandbox", "canvas", "bounce", "throw"],
      featured: false,
    },
    {
      id: "color-master",
      title: "Color Master",
      desc: "One target colour hides among convincing impostors. Can your eyes find the exact match?",
      category: "Puzzle",
      color: "var(--amber)", tint: "var(--amber-tint)",
      icon: "color-master",
      path: "experiments/color-master/",
      tags: ["color", "colour", "match", "eyes", "perception", "puzzle", "swatch"],
      featured: false,
    },
    {
      id: "decision-machine",
      title: "Decision Machine",
      desc: "Feed it your options, pull the lever, and let a dramatic drum decide your fate.",
      category: "Random",
      color: "var(--pink)", tint: "var(--pink-tint)",
      icon: "decision-machine",
      path: "experiments/decision-machine/",
      tags: ["decision", "random", "choose", "wheel", "spin", "picker", "confetti"],
      featured: false,
    },
    {
      id: "random-planets",
      title: "Random Planets",
      desc: "Roll an infinite galaxy: procedurally painted planets with names, climates and civilisations.",
      category: "Random",
      color: "var(--teal)", tint: "var(--teal-tint)",
      icon: "random-planets",
      path: "experiments/random-planets/",
      tags: ["planet", "space", "generator", "galaxy", "procedural", "universe", "stars"],
      featured: true,
    },
    {
      id: "tiny-drawing",
      title: "Tiny Drawing",
      desc: "A silky little canvas with brushes, colours, undo and one-tap PNG export.",
      category: "Creative",
      color: "var(--brand)", tint: "var(--brand-tint)",
      icon: "tiny-drawing",
      path: "experiments/tiny-drawing/",
      tags: ["draw", "drawing", "paint", "brush", "canvas", "sketch", "art", "doodle"],
      featured: false,
    },
    {
      id: "password-lab",
      title: "Password Lab",
      desc: "Watch a password get scored live: entropy, crack times and weak spots. 100% on-device.",
      category: "Learn",
      color: "var(--teal)", tint: "var(--teal-tint)",
      icon: "password-lab",
      path: "experiments/password-lab/",
      tags: ["password", "security", "entropy", "strength", "privacy", "crack", "safe"],
      featured: false,
    },
    {
      id: "number-guess",
      title: "Number Guess",
      desc: "Higher or lower? Hunt a hidden number through a shrinking range — par is waiting.",
      category: "Puzzle",
      color: "var(--amber)", tint: "var(--amber-tint)",
      icon: "number-guess",
      path: "experiments/number-guess/",
      tags: ["number", "guess", "higher", "lower", "logic", "binary", "search", "math"],
      featured: false,
    },
    {
      id: "word-mixer",
      title: "Word Mixer",
      desc: "Brew new concepts by mixing the things you own. A whole dictionary hides in your drawer.",
      category: "Creative",
      color: "var(--coral)", tint: "var(--coral-tint)",
      icon: "word-mixer",
      path: "experiments/word-mixer/",
      tags: ["word", "mix", "combine", "craft", "discovery", "brew", "recipe", "merge"],
      featured: false,
    },
  ];

  FL.byExperimentId = (id) => FL.registry.find((e) => e.id === id) || null;
  FL.categories = () => Array.from(new Set(FL.registry.map((e) => e.category)));
})(window.FunLab);
