/* FunLab service worker — generated by tools/build.py. Do not edit by hand. */
"use strict";

const VERSION = "funlab-7a9b1ad002";
const PRECACHE = [
  "404.html",
  "about.html",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/favicon.svg",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-maskable-192.png",
  "assets/icons/icon-maskable-512.png",
  "assets/og/og-cover.png",
  "contact.html",
  "css/experiments.css",
  "css/styles.css",
  "experiments/click-rush/index.html",
  "experiments/color-master/index.html",
  "experiments/decision-machine/index.html",
  "experiments/gravity-playground/index.html",
  "experiments/number-guess/index.html",
  "experiments/password-lab/index.html",
  "experiments/random-planets/index.html",
  "experiments/reaction-lab/index.html",
  "experiments/tiny-drawing/index.html",
  "experiments/word-mixer/index.html",
  "index.html",
  "js/core/cards.js",
  "js/core/fullscreen.js",
  "js/core/funlab.js",
  "js/core/icons.js",
  "js/core/modal.js",
  "js/core/nav.js",
  "js/core/pwa.js",
  "js/core/registry.js",
  "js/core/scores.js",
  "js/core/sound.js",
  "js/core/storage.js",
  "js/core/sw-register.js",
  "js/core/theme.js",
  "js/core/toast.js",
  "js/experiments/click-rush.js",
  "js/experiments/color-master.js",
  "js/experiments/decision-machine.js",
  "js/experiments/gravity-playground.js",
  "js/experiments/number-guess.js",
  "js/experiments/password-lab.js",
  "js/experiments/random-planets.js",
  "js/experiments/reaction-lab.js",
  "js/experiments/tiny-drawing.js",
  "js/experiments/word-mixer-recipes.js",
  "js/experiments/word-mixer.js",
  "manifest.json",
  "offline.html",
  "privacy.html",
  "sw.js"
];

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // Cache files one by one so a single hiccup cannot break the install.
    await Promise.allSettled(PRECACHE.map((url) => cache.add(url)));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  if (req.headers.has("range")) return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Pages: network first, fall back to cache, then to the offline page.
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(VERSION);
        cache.put(req, fresh.clone());
        return fresh;
      } catch (err) {
        const cached = await caches.match(req, { ignoreSearch: true });
        if (cached) return cached;
        const offline = await caches.match("offline.html");
        return offline || Response.error();
      }
    })());
    return;
  }

  // Static assets: stale-while-revalidate.
  event.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const cached = await cache.match(req, { ignoreSearch: false });
    const network = fetch(req).then((res) => {
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }).catch(() => undefined);
    return cached || (await network) || Response.error();
  })());
});
